apiVersion: apps/v1
kind: Deployment
metadata:
  name: workoutui-deployment
spec:
  selector:
    matchLabels:
      app: workoutui
  replicas: 2
  template:
    metadata:
      labels:
        app: workoutui
    spec:
      containers:
        - name: workoutui
          image: f # To be taken from dockerhub or gitlab
          ports:
            - containerPort: 8080
