apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: lordrex/workout-fastapi:1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "250m"
