apiVersion: apps/v1
kind: Deployment
metadata:
  name: workoutui-deployment
spec:
  selector:
    matchLabels:
      app: workoutui
  replicas: 2
  template:
    metadata:
      labels:
        app: workoutui
    spec:
      containers:
        - name: workoutui
          image: lordrex/workout-nextjs:v1.0.0 # To be taken from dockerhub or gitlab
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "350Mi"
              cpu: "250m"
